### PR TITLE
Sorting tasks

### PR DESCRIPTION
**Pull request by elk15**
Hello,
I have made a function that will sort the tasks in a dictionary in descending order based on their priority.

### CODE REVIEW

**Review by Bluejee — CHANGES_REQUESTED** [review]
The code seems fine, but as I will have to add some HTML code as well. 
So can you edit the pull request to merge with the branch Add_Sort_Feature that I have?

**Comment by elk15** [comment]
Ok, I changed it.

**Review by Bluejee — APPROVED** [review]
The merge branch seems to be correct.

**Comment by Bluejee** [comment]
Thank you 😄 

> Ok, I changed it.

**Pull request merged**
